default_principal:
    path:   /
    defaults: { _controller: "AppBundle:Comunitat:principal"}
    methods:  GET

default_post:
    path:   /postverification
    defaults: { _controller: "AppBundle:Comunitat:postverification"}
    methods:  POST

default_gestio:
    path:   /gestio
    defaults: { _controller: "AppBundle:Comunitat:gestio"}
    methods:  GET

default_gestio_noticies:
    path:   /gestioNoticies
    defaults: { _controller: "AppBundle:Comunitat:gestioNoticies"}
    methods:  GET
