default_principal:
    path:   /
    defaults: { _controller: "AppBundle:Comunitat:principal"}
    methods:  GET

default_noticia:
    path:   /noticiaverification
    defaults: { _controller: "AppBundle:Comunitat:noticiaverification"}
    methods:  POST

default_gestio:
    path:   /gestio
    defaults: { _controller: "AppBundle:Comunitat:gestio"}
    methods:  GET

default_follow:
    path:   /follow
    defaults: { _controller: "AppBundle:Comunitat:follow"}
    methods:  GET

default_resultat_c:
    path:   /searchresult
    defaults: { _controller: "AppBundle:User:searchresult"}
    methods:  POST

default_comunitat_verification:
    path:   /comunitatverification
    defaults: { _controller: "AppBundle:Comunitat:comunitatverification"}
    methods:  POST