default_perfil:
    path:   /
    defaults: { _controller: "AppBundle:Perfil:perfil"}
    methods:  GET

default_gestiouser:
    path:   /gestiouser
    defaults: { _controller: "AppBundle:Perfil:gestiouser"}
    methods:  GET

default_postverification:
    path:   /postverification
    defaults: { _controller: "AppBundle:Perfil:postverification"}
    methods:   POST

default_gestiouserverification:
    path:   /gestiouserverification
    defaults: { _controller: "AppBundle:Perfil:gestiouserverification"}
    methods:  POST

default_resultat:
    path:   /searchresult
    defaults: { _controller: "AppBundle:User:searchresult"}
    methods:  POST