default_perfil:
    path:   /
    defaults: { _controller: "AppBundle:Perfil:perfil"}
    methods:  GET

default_gestiouser:
    path:   /gestiouser
    defaults: { _controller: "AppBundle:Perfil:gestiouser"}
    methods:  GET

default_postverification:
    path:   /postverification
    defaults: { _controller: "AppBundle:Perfil:postverification"}
    methods:   POST

default_gestiouserverification1:
    path:   /gestiouserverification1
    defaults: { _controller: "AppBundle:Perfil:gestiouserverification1"}
    methods:  POST

default_gestiouserverification2:
    path:   /gestiouserverification2
    defaults: { _controller: "AppBundle:Perfil:gestiouserverification2"}
    methods:  POST

default_resultat:
    path:   /searchresult
    defaults: { _controller: "AppBundle:User:searchresult"}
    methods:  POST

default_logout_perfil:
    path:   /logout
    defaults: { _controller: "AppBundle:User:logout"}
    methods:  GET