default_login:
    path:   /
    defaults: { _controller: "AppBundle:User:login"}
    methods:  GET

default_login_verification:
    path:   /loginverification
    defaults: { _controller: "AppBundle:User:loginverification"}
    methods:  POST

default_registre_verification:
    path:   /registreverification
    defaults: { _controller: "AppBundle:User:registreverification"}
    methods:  POST

default_gestio:
    path:   /gestio
    defaults: {_controller: "AppBundle:User:gestio"}
    methods:  GET