default_login:
    path:   /login
    defaults: { _controller: "AppBundle:User:login"}
    methods:  GET

default_registre:
    path:   /registre
    defaults: { _controller: "AppBundle:User:registre"}
    methods:  GET

default_login_verification:
    path:   /loginverification
    defaults: { _controller: "AppBundle:User:loginverification"}
    methods:  GET

default_registre_verification:
    path:   /registreverification
    defaults: { _controller: "AppBundle:User:registreverification"}
    methods:  GET