BackendBundle\Entity\CommentsPost:
    type: entity
    table: comments_post
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idPost:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_post
        idUser:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_user
        comment:
            type: string
            nullable: false
            length: 9999
            options:
                fixed: false
        createDate:
            type: datetime
            nullable: false
            column: create_date
    lifecycleCallbacks: {  }
