BackendBundle\Entity\CommentsNoticia:
    type: entity
    table: comments_noticia
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idNoticia:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_noticia
        idUser:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_user
        comment:
            type: string
            nullable: false
            length: 9999
            options:
                fixed: false
        createDate:
            type: datetime
            nullable: false
            column: create_date
    lifecycleCallbacks: {  }
