BackendBundle\Entity\Groupchat:
    type: entity
    table: groupchat
    indexes:
        id_user:
            columns:
                - id_user
        id_group:
            columns:
                - id_group
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        missage:
            type: string
            nullable: false
            length: 9999
            options:
                fixed: false
        createDate:
            type: datetime
            nullable: false
            column: create_date
    manyToOne:
        idGroup:
            targetEntity: InfoGroup
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_group:
                    referencedColumnName: id
            orphanRemoval: false
        idUser:
            targetEntity: InfoUsuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_user:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
