BackendBundle\Entity\InfoCommunity:
    type: entity
    table: info_community
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 999
            options:
                fixed: false
        idAdmin:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_admin
        description:
            type: string
            nullable: true
            length: 9999
            options:
                fixed: false
        createDate:
            type: datetime
            nullable: false
            column: create_date
        imgAvatar:
            type: string
            nullable: false
            length: 999
            options:
                fixed: false
                default: /uploads/community/default.png
            column: img_avatar
        imgTitle:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: img_title
    lifecycleCallbacks: {  }
