BackendBundle\Entity\InfoUsuario:
    type: entity
    table: info_usuario
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        user:
            type: string
            nullable: false
            length: 999
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 999
            options:
                fixed: false
        name:
            type: string
            nullable: true
            length: 999
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 999
            options:
                fixed: false
        active:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
        icona:
            type: string
            nullable: true
            length: 999
            options:
                fixed: false
                default: uploads/usericona/avatardefault.png
    lifecycleCallbacks: {  }
