BackendBundle\Entity\Noticia:
    type: entity
    table: noticia
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idCommunity:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: id_community
        createDate:
            type: datetime
            nullable: true
            column: create_date
        title:
            type: string
            nullable: true
            length: 999
            options:
                fixed: false
        imgRoute:
            type: string
            nullable: true
            length: 999
            options:
                fixed: false
            column: img_route
        imgAlt:
            type: string
            nullable: true
            length: 999
            options:
                fixed: false
                default: 'img of noticia'
            column: img_alt
        message:
            type: string
            nullable: true
            length: 999
            options:
                fixed: false
    lifecycleCallbacks: {  }
