BackendBundle\Entity\Post:
    type: entity
    table: post
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idUser:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_user
        createDate:
            type: datetime
            nullable: true
            column: create_date
        imgRoute:
            type: string
            nullable: true
            length: 999
            options:
                fixed: false
            column: img_route
        messages:
            type: string
            nullable: false
            length: 999
            options:
                fixed: false
        imgAlt:
            type: string
            nullable: true
            length: 999
            options:
                fixed: false
                default: 'img of post'
            column: img_alt
    lifecycleCallbacks: {  }
