app_user:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix: /

app_perfil:
    resource: "@AppBundle/Resources/config/routing/perfil.yml"
    prefix: /perfil

app_comunitat:
    resource: "@AppBundle/Resources/config/routing/comunitat.yml"
    prefix: /comunitat
 