AppBundle\Entity\InfoGame:
    type: entity
    table: info_game
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: integer
            nullable: false
            options:
                unsigned: false
        description:
            type: integer
            nullable: false
            options:
                unsigned: false
        type:
            type: string
            nullable: false
            length: 99
            options:
                fixed: false
    lifecycleCallbacks: {  }
