AppBundle\Entity\Post:
    type: entity
    table: post
    indexes:
        id_user:
            columns:
                - id_user
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createDate:
            type: datetime
            nullable: false
            column: create_date
        imgRoute:
            type: string
            nullable: false
            length: 999
            options:
                fixed: false
            column: img_route
        videoRoute:
            type: string
            nullable: false
            length: 999
            options:
                fixed: false
            column: video_route
        missage:
            type: string
            nullable: false
            length: 999
            options:
                fixed: false
    manyToOne:
        idUser:
            targetEntity: InfoUsuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_user:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
