AppBundle\Entity\Userchat:
    type: entity
    table: userchat
    indexes:
        id_user_e:
            columns:
                - id_user_e
        id_user_e_2:
            columns:
                - id_user_e
        id_user_e_3:
            columns:
                - id_user_e
        id_user_r:
            columns:
                - id_user_r
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        missage:
            type: string
            nullable: false
            length: 999
            options:
                fixed: false
        createDate:
            type: datetime
            nullable: false
            column: create_date
    manyToOne:
        idUserR:
            targetEntity: InfoUsuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_user_r:
                    referencedColumnName: id
            orphanRemoval: false
        idUserE:
            targetEntity: InfoUsuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_user_e:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
